print("Introduce y1")
y1 = float(input())
print("Introduce y2")
y2 = int(input())
print("Introduce x1")
x1 = float(input())
print("introduce x2")
x2 = float(input())
p = (y1 - y2) / (x1 - x2)
print("La pendiente es ", end='', flush=True)
print(p)
