print("introduce numerador")
rNum = float(input())
print("introduce denominador")
rDen = float(input())
print("introduce numerador 2")
rNum2 = float(input())
print("Introduce denominador 2")
rDen2 = float(input())
rSum = rNum / rDen + rNum2 / rDen2
print("El resultado de la suma es ", end='', flush=True)
print(rSum)
rRest = rNum / rDen - rNum2 / rDen2
print("El resulatdo de la resta es ", end='', flush=True)
print(rRest)
rDiv = rNum / rDen / (rNum2 / rDen2)
print("El resultado de la division es ", end='', flush=True)
print(rDiv)
rMult = rNum / rDen * (rNum2 / rDen2)
print("El resultado de la multiplicacion es ", end='', flush=True)
print(rMult)
